//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalizatorNurkowaniaWFA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalizatorNurkowaniaWFA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powietrze.
        /// </summary>
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cisnienie zewnetrzne [bar].
        /// </summary>
        internal static string ambientPreasureExcel {
            get {
                return ResourceManager.GetString("ambientPreasureExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasycenia tkanek.
        /// </summary>
        internal static string compartmentName {
            get {
                return ResourceManager.GetString("compartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Głębokość [m].
        /// </summary>
        internal static string depthWithUnit {
            get {
                return ResourceManager.GetString("depthWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        internal static string EAN {
            get {
                return ResourceManager.GetString("EAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Głebokość końcowa [m].
        /// </summary>
        internal static string finialDepthExcel {
            get {
                return ResourceManager.GetString("finialDepthExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zestawienie gazów.
        /// </summary>
        internal static string gasesMixName {
            get {
                return ResourceManager.GetString("gasesMixName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa mieszanki.
        /// </summary>
        internal static string gasNameExcel {
            get {
                return ResourceManager.GetString("gasNameExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawartość He.
        /// </summary>
        internal static string HeNameExcel {
            get {
                return ResourceManager.GetString("HeNameExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Głebokość poczatkowa [m].
        /// </summary>
        internal static string initialDepthExcel {
            get {
                return ResourceManager.GetString("initialDepthExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - wartość.
        /// </summary>
        internal static string MValue {
            get {
                return ResourceManager.GetString("MValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawartość N2.
        /// </summary>
        internal static string N2NameExcel {
            get {
                return ResourceManager.GetString("N2NameExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawartość O2.
        /// </summary>
        internal static string O2NameExcel {
            get {
                return ResourceManager.GetString("O2NameExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cisnienie parcjalne N2 [bar].
        /// </summary>
        internal static string pPN2Excel {
            get {
                return ResourceManager.GetString("pPN2Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cisnienie [bar].
        /// </summary>
        internal static string preasureBar {
            get {
                return ResourceManager.GetString("preasureBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil nurkowania.
        /// </summary>
        internal static string profileName {
            get {
                return ResourceManager.GetString("profileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas [min].
        /// </summary>
        internal static string timeWithUnit {
            get {
                return ResourceManager.GetString("timeWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMX.
        /// </summary>
        internal static string TMX {
            get {
                return ResourceManager.GetString("TMX", resourceCulture);
            }
        }
    }
}
